### ISSUE TITLE
To-do list on early version

### ISSUE THREAD

**Issue by dekguh** [dekguh/Leaflet.MoveMarker#2]
current version: 0.0.12 (beta)
## **To-do list marker features**
- [x] animate moving marker
- [x] follow marker when moving (need more improve)
- [x] duration by speed (km)
- [x] rotation marker (need more improve)
- [x] disabled animate marker
- [x] stop animate marker
- [x] method moveTo (params: nextLatLng, options : { duration or speed })
- [x] show/hide marker

## **To-do list polyline features**
- [x] animate polyline/trail
- [x] show/hide polyline
- [x] stop animate polyline 
- [x] disabled animate polyline
- [x] max polyline line (old polyline will remove and replace new line)

## **Other To-do**
- [x] create example with real case and basic usage
- [x] create documentation
- [x] fix disable follow marker bug with animate (minor) [PR 9](https://github.com/dekguh/L.MoveMarker/pull/9)
- [x] dont execute rotation if addMore value rotateAngle same with current context rotateAngle (minor)
- [x] https://github.com/dekguh/L.MoveMarker/issues/12
- [x] #19 

## **what next?**
- [ ] improve the follow marker
- [ ] #25
- [ ] improve animate polyline when on zoom
- [ ] #26
- [ ] demo version on vue and angular maybe
- [ ] write testing

note: the item with checked has been merged with current version

## **If you love**
if you like what i do with my stuff, you can donate me a beer 🗿
